[package]
name = "hawk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Hawk error tracking SDK for Rust"

[dependencies]
hawk_core.workspace = true
hawk_panic.workspace = true
